weather/urls.py
from django.urls import path

from . import views

app_name = "weather"
urlpatterns = [
    path("", views.home, name="home"),
    path("add-weather", views.add_weather, name="add-weather-data"),
    path("display", views.display_weather, name="display-weather"),
]

weatherApp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("weather.urls", namespace="weather")),
]

weather/models.py
from django.db import models


class City(models.Model):
    city_id = models.BigAutoField(
        db_column="City_id",
        auto_created=True,
        primary_key=True,
        serialize=False,
        verbose_name="ID",
    )
    name = models.CharField("City Name", max_length=64, db_column="City_name")
    coord = models.CharField(max_length=64, db_column="City_coord")
    country_code = models.CharField(max_length=6, db_column="City_country_code")

    class Meta:
        verbose_name_plural = "Cities"
        db_table = "City"

    def __str__(self):
        return str(self.name)


class Weather(models.Model):
    weather_id = models.BigAutoField(
        db_column="Weather_id",
        auto_created=True,
        primary_key=True,
        serialize=True,
        verbose_name="ID",
    )
    temp_min = models.BigIntegerField(db_column="Weather_temp_min")
    temp_max = models.BigIntegerField(db_column="Weather_temp_max")
    temp_feels = models.DecimalField(
        max_digits=5, decimal_places=2, db_column="Weather_temp_feels"
    )
    pressure = models.PositiveIntegerField(db_column="Weather_pressure")
    humidity = models.PositiveIntegerField(db_column="Weather_humidity")
    weather_main = models.CharField(max_length=64, db_column="Weather_weather_main")
    desc = models.CharField(max_length=64, db_column="Weather_desc")
    icon = models.CharField(max_length=10, db_column="Weathera_icon")
    city = models.OneToOneField("City", related_name="city", on_delete=models.CASCADE)
    wind = models.DecimalField(max_digits=5, decimal_places=2, db_column="Weather_wind")
    updated_at = models.DateTimeField(db_column="Weather_updated_at", auto_now_add=True)

    class Meta:
        verbose_name_plural = "Weather"
        db_table = "Weather"

    def __str__(self):
        return str(self.weather_id) + " - " + str(self.city.name)

weather/views.py
from django.contrib import messages
from django.forms.models import model_to_dict
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from render_block import render_block_to_string
from .models import City, Weather
from .util import utils


def get_city_weather_from_db(city_name: str):
    """fetch data from db"""
    try:
        weather = Weather.objects.get(city__name=city_name)
        data = utils.get_city_weather_dict(weather)
        return data
    except Weather.DoesNotExist:
        return None


def home(request):
    data = {}
    return render(request, "index.html", data)


@require_POST
def add_weather(request):
    city_name = request.POST.get("city")

    city_name = city_name.strip().title()
    if city_name == "":
        messages.error(request, "City name is empty")
        return redirect("weather:home")
    context_db = get_city_weather_from_db(city_name)
    
    context_api = {}
    if context_db is None:
        # call the api
        print("calling the API")
        data_api = utils.get_city_weather(city_name)
        if data_api is not None:
            city_json, weather_json = data_api

            city = City.objects.create(**city_json)

            # add the city object to the weather json
            weather_json["city"] = city
            weather = Weather.objects.create(**weather_json)

            city.save()
            weather.save()
            context_api =  {**city_json, **weather_json}
        else:
            return HttpResponse(
                """<h4 style="color: red;">Unable to reach Weather data provider. Ensure you have internet connection.</h4>"""
            )
    else:
        print("weather data loaded from db")
    
    context = context_db or context_api
    html = render_block_to_string("index.html", 'weather', context)
    return HttpResponse(html)
    # return render(request, "index.html", data_db)


def display_weather(request, data):
    return HttpResponseRedirect(reverse("weather:home"), data=data)

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="weather app">
    <!-- FONTS -->
    <!-- BOOTSTRAP CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <script type="text/javascript" src="{% static 'htmx.min.js' %}">
    </script>
    {% block headContent %}

    {% endblock headContent %}

    <title>
        {% block title %}
        base template
        {% endblock title %}
    </title>

    <style>

        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

@media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>



</head>

<body>
    
    {% include "header.html" %}


    <!-- MAIN -->
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 mb-10">

       {% include "messages.html" %}

        {% block main %}
        {% endblock main %}

    </main>
</div>
{% block scripts %}

{% endblock scripts %}

<script type="text/javascript" src="{% static 'bootstrap/popper.min.js'%}" defer>
</script>
<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}" defer>
</script>
<script type="text/javascript" src="{% static 'feather.min.js' %}" defer>
</script>

</body>
</html>

templates/header.html
    <!-- HEADER NAV -->
    <header class="navbar navbar-expand-md navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">AccuWeather</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"></div>
    </header>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Weather: ALL
{% endblock title %}


{% block main %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Weather Information for {{name}} </h1>
    <small>{{randomName}}</small>
</div>


<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-2">
        <div class="d-flex justify-content-even ">
            <form hx-post="{% url "weather:add-weather-data" %}" hx-target='#weather-info'>
                {% csrf_token %}
                <div class="form-group mb-2 mx-100">
                    <input type="text" class="form-control" required="true" name="city" placeholder="Enter the town name">
                </div>
                <input type="submit" role="button" class="btn btn-primary" value="submit">
            </form>
        </div>
    </div>
</div>

{% block weather %}
<div class="row container-fluid mb-100" id="weather-info">
    <div class="col ">
        <div class="card mb-6">
            <div class="card-body">
                <div class="card-title fw-bold h5">
                    Today's Weather in {{name}}
                </div>
                <h1 class="fw-bold mb-0">{{temp_feels}} <span>°</span></h1>
                <small class="text-muted fw-bold my-0">Feels like</small>

                <div class="row">
                    <div class="col border-top me-5 py-2">
                        <div class="d-flex align-items-center justify-content-between">
                            <div class="h6 me-3">
                                Country Code
                            </div>
                            <span>{{country_code}}</span>
                        </div>
                    </div>
                    <div class="col border-top me-5 py-2">
                        <div class="d-flex align-items-center justify-content-between">
                            <div class="h6 me-3">
                                Coordinate
                            </div>
                            <span>{{coord}}</span>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col border-top me-5 py-1">
                        <div class="d-flex align-items-center justify-content-between">
                            <div class="h6 me-3">
                                <img src="{% static 'icons/thermometer.svg' %}" alt="thermometer icon">
                                High/Low
                            </div>
                            <span>{{temp_max}}°/{{temp_min}}°</span>
                        </div>
                    </div>
                    <div class="col border-top me-5 py-1">
                        <div class="d-flex align-items-center justify-content-between">
                            <div class="h6 me-3">
                                Pressure
                            </div>
                            <span>{{pressure}}</span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col border-top me-5 py-1">
                        <div class="d-flex align-items-center justify-content-between">
                            <div class="h6 me-3">
                                <img src="{% static 'icons/thermometer.svg' %}" alt="thermometer icon">
                                Humidity
                            </div>
                            <span>{{humidity}}</span>
                        </div>
                    </div>
                    <div class="col border-top me-5 py-1">
                        <div class="d-flex align-items-center justify-content-between">
                            <div class="h6 me-3">
                                Forecast
                            </div>
                            <span>{{weather_main}} <img src="https://openweathermap.org/img/wn/{{icon}}.png" class="ms-2" alt="weather icons"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col border-top me-5 py-1">
                        <div class="d-flex align-items-center justify-content-between">
                            <div class="h6 me-3">
                                <img src="{% static 'icons/thermometer.svg' %}" alt="thermometer icon">
                                Description
                            </div>
                            <span>{{desc}}</span>
                        </div>
                    </div>
                    <div class="col border-top me-5 py-1">
                        <div class="d-flex align-items-center justify-content-between">
                            <div class="h6 me-3">
                                Wind
                            </div>
                            <span>{{wind}} km/h</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock weather%}
{% endblock main %}

templates/messages.html
 <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
            <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                <path
                    d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
            </symbol>
            <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
                <path
                    d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z" />
            </symbol>
            <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
                <path
                    d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
            </symbol>
        </svg>
        {% if messages %}
        {% for message in messages %}

        {% if message.level == 20 %}
        <!--INFO-->
        <div class="alert alert-primary d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Info:">
                <use xlink:href="#info-fill" /></svg>
            <div>
                {{ message }}
            </div>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% elif message.level == 25 %}
        <!--SUCCESS-->
        <div class="alert alert-success d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:">
                <use xlink:href="#check-circle-fill" /></svg>
            <div>
                {{ message }}
            </div>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        {% elif message.level == 40 %}
        <!--ERROR-->
        <div class="alert alert-warning d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:">
                <use xlink:href="#exclamation-triangle-fill" /></svg>
            <div>
                {{ message }}
            </div>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
        {% endfor %}
        {% endif%}